@startuml Διάγραμμα Ευρωστίας ΠΧ-7: Εφαρμογή Κωδικού Έκπτωσης

' Styling
skinparam actorStyle awesome
skinparam rectangle {
    BackgroundColor<<boundary>> LightYellow
    BackgroundColor<<control>> LightGreen
    BackgroundColor<<entity>> LightBlue
    BorderColor Black
}

' Actors
actor "Μέλος" as member
actor "Πύλη Πληρωμών" as payment
actor "Σύστημα Email" as email

' Boundary Objects (UI)
rectangle "Καρτέλα Συνδρομής" <<boundary>> as membershipTab
rectangle "Λίστα Ενεργών Κωδικών" <<boundary>> as activeCodesList
rectangle "Κάρτα Κωδικού Προσφοράς" <<boundary>> as promoCodeCard
rectangle "Πεδίο Εισαγωγής Κωδικού" <<boundary>> as codeInputField
rectangle "Κουμπί 'Εφαρμογή'" <<boundary>> as applyButton
rectangle "Ανάλυση Έκπτωσης" <<boundary>> as discountBreakdown
rectangle "Modal Επιτυχίας" <<boundary>> as successModal
rectangle "Οθόνη Πληρωμής" <<boundary>> as paymentScreen
rectangle "Μήνυμα Σφάλματος" <<boundary>> as errorMsg

' Control Objects (Logic)
rectangle "Διαχειριστής Κωδικών" <<control>> as codeManager
rectangle "Επικυρωτής Κωδικού" <<control>> as codeValidator
rectangle "Υπολογιστής Έκπτωσης" <<control>> as discountCalculator
rectangle "Έλεγχος Ημερομηνιών" <<control>> as dateChecker
rectangle "Επεξεργαστής Πληρωμής" <<control>> as paymentProcessor
rectangle "Διαχειριστής Email" <<control>> as emailManager

' Entity Objects (Data)
rectangle "Κωδικός Προσφοράς" <<entity>> as promoCode
rectangle "Καμπάνια" <<entity>> as campaign
rectangle "Έκπτωση" <<entity>> as discount
rectangle "Συνδρομή" <<entity>> as subscription
rectangle "Τιμή" <<entity>> as price
rectangle "Τελική Τιμή" <<entity>> as finalPrice
rectangle "Συναλλαγή" <<entity>> as transaction
rectangle "Email Επιβεβαίωσης" <<entity>> as confirmEmail

' Ροή 1: Περιήγηση στη Συνδρομή
member --> membershipTab : "1. Ανοίγει\nΣυνδρομή"
membershipTab --> codeManager : "2. Φορτώνει\nδιαθέσιμους κωδικούς"
codeManager --> campaign : "3. Ανακτά\nενεργές καμπάνιες"
campaign --> promoCode : "4. Φορτώνει\nκωδικούς"

' Ροή 2: Εμφάνιση Λίστας Κωδικών
promoCode --> activeCodesList : "5. Εμφανίζει\nλίστα 8+ κωδικών"
activeCodesList --> promoCodeCard : "6. Για κάθε κωδικό:\n- Όνομα καμπάνιας\n- Περιγραφή\n- Ποσοστό έκπτωσης\n- Ημερομηνία λήξης\n- Εικονίδιο αντιγραφής"

' Ροή 3: Κλικ σε Κωδικό (auto-fill)
member --> promoCodeCard : "7. Κλικ στην\nκάρτα κωδικού"
promoCodeCard --> codeInputField : "8. Αυτόματη\nσυμπλήρωση"
codeInputField --> member : "9. Εμφανίζει\nκωδικό στο πεδίο"

' Ροή 4: Χειροκίνητη Εισαγωγή (εναλλακτικά)
member --> codeInputField : "10. Πληκτρολογεί\nκωδικό"

' Ροή 5: Εφαρμογή Κωδικού
member --> applyButton : "11. Κλικ 'Εφαρμογή'"
applyButton --> codeValidator : "12. Επικύρωση"
codeValidator --> promoCode : "13. Αναζήτηση\nκωδικού"

' Ροή 6a: Μη Έγκυρος Κωδικός (extend)
promoCode --> codeValidator : "14a. Δεν βρέθηκε"
codeValidator --> errorMsg : "15a. Σφάλμα"
errorMsg --> member : "16a. 'Μη έγκυρος\nκωδικός'"

' Ροή 6b: Έλεγχος Ημερομηνιών
promoCode --> codeValidator : "14b. Βρέθηκε"
codeValidator --> dateChecker : "15b. Έλεγχος\nισχύος"
dateChecker --> campaign : "16b. Ανακτά\nημερομηνίες"

' Ροή 6c: Ληγμένος Κωδικός (extend)
campaign --> dateChecker : "17c. Λήξη <\nσήμερα"
dateChecker --> errorMsg : "18c. Σφάλμα"
errorMsg --> member : "19c. 'Ο κωδικός\nέχει λήξει'"

' Ροή 6d: Προγραμματισμένος Κωδικός (extend)
campaign --> dateChecker : "17d. Έναρξη >\nσήμερα"
dateChecker --> errorMsg : "18d. Σφάλμα"
errorMsg --> member : "19d. 'Ο κωδικός\nδεν είναι ακόμα\nενεργός'"

' Ροή 7: Έγκυρος Κωδικός - Υπολογισμός
campaign --> dateChecker : "17e. Εντός\nισχύος"
dateChecker --> codeValidator : "18e. Έγκυρος"
codeValidator --> discountCalculator : "19. Υπολογισμός\nέκπτωσης"
discountCalculator --> promoCode : "20. Ανακτά %"
promoCode --> discountCalculator : "21. Επιστρέφει\nποσοστό"
discountCalculator --> subscription : "22. Ανακτά\nτιμή συνδρομής"
subscription --> price : "23. Επιστρέφει\nτιμή"
discountCalculator --> discount : "24. Υπολογίζει\nέκπτωση"
discountCalculator --> finalPrice : "25. Υπολογίζει\nτελική τιμή"

' Ροή 8: Εμφάνιση Ανάλυσης
discountCalculator --> discountBreakdown : "26. Εμφανίζει\nανάλυση"
discountBreakdown --> member : "27. Προβάλλει:\n- Αρχική τιμή\n- Έκπτωση %\n- Ποσό έκπτωσης\n- Τελική τιμή\n- Εξοικονόμηση/μήνα"

' Ροή 9: Επιβεβαίωση και Πληρωμή
member --> discountBreakdown : "28. Επιβεβαιώνει"
discountBreakdown --> paymentScreen : "29. Μετάβαση\nσε πληρωμή"
member --> paymentScreen : "30. Εισάγει\nστοιχεία"
paymentScreen --> paymentProcessor : "31. Επεξεργασία"
paymentProcessor --> payment : "32. Καλεί API\nμε έκπτωση"
payment --> paymentProcessor : "33. Επιτυχία"
paymentProcessor --> transaction : "34. Καταγράφει\nσυναλλαγή"
transaction --> discount : "35. Συνδέει\nέκπτωση"

' Ροή 10: Email Επιβεβαίωσης
paymentProcessor --> emailManager : "36. Δημιουργία\nemail"
emailManager --> confirmEmail : "37. Δημιουργεί\nμε λεπτομέρειες"
confirmEmail --> email : "38. Στέλνει"

' Ροή 11: Modal Επιτυχίας
paymentProcessor --> successModal : "39. Εμφανίζει\nεπιτυχία"
successModal --> member : "40. Μήνυμα:\n- Επιτυχής εγγραφή\n- Εξοικονομήσατε €X\n- Email σταλμένο\n- Λήξη κωδικού"

@enduml
